
package ru.rsatu.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentMarksService", targetNamespace = "http://rsatu.ru/", wsdlLocation = "file:/home/rabbit/stud/java/5_0/soapclient/src/main/resources/studentMarks.wsdl")
public class StudentMarksService
    extends Service
{

    private final static URL STUDENTMARKSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTMARKSSERVICE_EXCEPTION;
    private final static QName STUDENTMARKSSERVICE_QNAME = new QName("http://rsatu.ru/", "StudentMarksService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/rabbit/stud/java/5_0/soapclient/src/main/resources/studentMarks.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTMARKSSERVICE_WSDL_LOCATION = url;
        STUDENTMARKSSERVICE_EXCEPTION = e;
    }

    public StudentMarksService() {
        super(__getWsdlLocation(), STUDENTMARKSSERVICE_QNAME);
    }

    public StudentMarksService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTMARKSSERVICE_QNAME, features);
    }

    public StudentMarksService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTMARKSSERVICE_QNAME);
    }

    public StudentMarksService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTMARKSSERVICE_QNAME, features);
    }

    public StudentMarksService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentMarksService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentMarks
     */
    @WebEndpoint(name = "StudentMarksPort")
    public StudentMarks getStudentMarksPort() {
        return super.getPort(new QName("http://rsatu.ru/", "StudentMarksPort"), StudentMarks.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentMarks
     */
    @WebEndpoint(name = "StudentMarksPort")
    public StudentMarks getStudentMarksPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rsatu.ru/", "StudentMarksPort"), StudentMarks.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTMARKSSERVICE_EXCEPTION!= null) {
            throw STUDENTMARKSSERVICE_EXCEPTION;
        }
        return STUDENTMARKSSERVICE_WSDL_LOCATION;
    }

}
